---
- name: Install server default packges
  become: yes
  apt:
    name:
      - zip
      - unzip
    state: latest
  tags:
    - common

- name: Set timezone to Europe/Stockholm
  become: yes
  timezone:
    name: Europe/Stockholm
  tags:
    - common
