---
- name: Install MariaDB server
  become: yes
  apt:
    name:
      - mariadb-server
    state: latest
  tags:
    - mariadb

- name: Install required MariaDB Python libraries
  become: yes
  apt:
    name:
      - python3-mysqldb
    state: latest
  tags:
    - mariadb

- name: Determine required MariaDB Python libraries.
  set_fact:
    deb_mysql_python_package: "python3-mysqldb"
  tags:
    - mariadb

#- name: Edit database root user plugin from auth_socket to mysql_native_password
#  become: yes
#  mysql_user:
##    login_user: root
##    login_password: "{{ mysql_root_password }}"
#    name: root
#    password: "{{ mysql_root_password }}"
#    priv: "*.*:ALL,GRANT"
#    host: "%"
##  failed_when: no
#  tags:
#    - mariadb

- name: Set innodb_file_per_table variable
  become: yes
  mysql_variables:
#    login_user: root
#    login_password: "{{ mysql_root_password }}"
    variable: innodb_file_per_table
    value: "ON"
  tags:
    - mariadb

#- name: Set innodb_... variables
#  become: yes
#  mysql_variables:
#    variable: "{{ item.variable }}"
#    value: "{{ item.value }}"
#  with_items:
##    - {variable: innodb_file_format, value: "Barracuda"}
#    - {variable: innodb_file_per_table, value: "ON"}
##    - {variable: innodb_large_prefix, value: "ON"}
#  tags:
#    - mariadb

- name: Create a new database
  become: yes
  mysql_db:
#    login_user: root
#    login_password: "{{ mysql_root_password }}"
    name: "{{ mysql_database_name }}"
    encoding: "{{ mysql_encoding }}"
    collation: "{{ mysql_collation }}"
  tags:
    - mariadb

- name: Create new database-user with all database privileges and 'WITH GRANT OPTION'
  become: yes
  mysql_user:
#    login_user: root
#    login_password: "{{ mysql_root_password }}"
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "*.*:ALL,GRANT"
    host: "%"
  tags:
    - mariadb
