---
- name: Add PHP 8.0 repository from PPA
  become: yes
  apt_repository:
    repo: ppa:ondrej/php
  tags:
    - php8.0

- name: Install PHP 8.0 packages
  become: yes
  apt:
    name:
      - php8.0
      - php8.0-cli
      - php8.0-curl
      - php8.0-gd
      - php8.0-mbstring
      - php8.0-mysql
      - php8.0-odbc
      - php8.0-xml
      - php8.0-zip
      - php8.0-bz2
      - php8.0-intl
      - php8.0-apcu
      - php8.0-redis
      - php8.0-msgpack
      - php8.0-imagick
      - php-pear
    state: latest
  notify: Restart Apache2
  tags:
    - php8.0

- name: Set PHP 8.0 configuration in php.ini
  become: yes
  ini_file:
    path: /etc/php/8.0/apache2/php.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: PHP, option: memory_limit, value: 512M }
    - { section: PHP, option: max_execution_time, value: 100M }
    - { section: PHP, option: post_max_size, value: 100M }
    - { section: Date, option: date.timezone, value: Europe/Stockholm }
  notify: Restart Apache2
  tags:
    - php8.0
