---
- name: Add PHP 7 repository from PPA
  become: yes
  apt_repository:
    repo: ppa:ondrej/php
  tags:
    - php7.4

- name: Install PHP 7.4 packages
  become: yes
  apt:
    name:
      - php7.4
      - php7.4-cli
      - php7.4-curl
      - php7.4-gd
      - php7.4-mbstring
      - php7.4-mysql
      - php7.4-odbc
      - php7.4-xml
      - php7.4-zip
      - php7.4-bz2
      - php7.4-intl
      - php7.4-apcu
      - php7.4-redis
      - php7.4-msgpack
      - php-pear
      - php7.4-imagick
    state: latest
  notify: Restart Apache
  tags:
    - php7.4

- name: Set PHP configuration in php.ini
  become: yes
  ini_file:
    path: /etc/php/7.4/apache2/php.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: PHP, option: memory_limit, value: 512M }
    - { section: PHP, option: max_execution_time, value: 100M }
    - { section: PHP, option: post_max_size, value: 100M }
    - { section: Date, option: date.timezone, value: Europe/Stockholm }
  notify: Restart Apache
  tags:
    - php7.4
